version: '1.0.{build}'
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./TrailTracker.API/TrailTracker.API.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./TrailTracker.API/TrailTracker.API.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '\artifacts'
   name: TrailTracker.API
   type: WebDeployPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./TrailTracker.API/TrailTracker.API.Tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd TrailTracker.API.Tests
  - cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy: off